# IDX_STOCKS = {
#     "BBCA.JK": "Bank Central Asia",
#     "BBRI.JK": "Bank Rakyat Indonesia",
#     "TLKM.JK": "Telekomunikasi Indonesia",
#     "ASII.JK": "Astra International",
#     "BMRI.JK": "Bank Mandiri",
#     "UNVR.JK": "Unilever Indonesia",
#     "BBNI.JK": "Bank Negara Indonesia",
#     "GOTO.JK": "GoTo Gojek Tokopedia",
#     "BYAN.JK": "Bayan Resources",
#     "PGAS.JK": "Perusahaan Gas Negara",
#     "ADRO.JK": "Adaro Energy",
#     "ICBP.JK": "Indofood CBP",
#     "INDF.JK": "Indofood Sukses Makmur",
#     "KLBF.JK": "Kalbe Farma",
#     "EXCL.JK": "XL Axiata",
#     "SMGR.JK": "Semen Indonesia",
#     "MNCN.JK": "Media Nusantara Citra",
#     "BSDE.JK": "Bumi Serpong Damai",
#     "PTBA.JK": "Bukit Asam",
#     "GGRM.JK": "Gudang Garam",
#     "HMSP.JK": "HM Sampoerna",
#     "INTP.JK": "Indocement Tunggal",
#     "CPIN.JK": "Charoen Pokphand Indonesia",
#     "JPFA.JK": "Japfa Comfeed",
#     "JSMR.JK": "Jasa Marga",
#     "ANTM.JK": "Aneka Tambang",
#     "MEDC.JK": "Medco Energi",
#     "MIKA.JK": "Mitra Keluarga Karyasehat",
#     "SIDO.JK": "Industri Jamu Sido Muncul",
#     "TOWR.JK": "Sarana Menara Nusantara",
# }

IDX_STOCKS = {
    # ── BANKING (20) ──────────────────────────────────────────────
    "BBCA.JK": "Bank Central Asia",
    "BBRI.JK": "Bank Rakyat Indonesia",
    "BMRI.JK": "Bank Mandiri",
    "BBNI.JK": "Bank Negara Indonesia",
    "BBTN.JK": "Bank Tabungan Negara",
    "BNGA.JK": "Bank CIMB Niaga",
    "BDMN.JK": "Bank Danamon Indonesia",
    "NISP.JK": "Bank OCBC NISP",
    "PNBN.JK": "Bank Pan Indonesia",
    "BJBR.JK": "Bank Pembangunan Daerah Jawa Barat",
    "BJTM.JK": "Bank Pembangunan Daerah Jawa Timur",
    "MEGA.JK": "Bank Mega",
    "BTPS.JK": "Bank BTPN Syariah",
    "BNII.JK": "Bank Maybank Indonesia",
    "AGRO.JK": "Bank Rakyat Indonesia Agroniaga",
    "BMAS.JK": "Bank Maspion Indonesia",
    "BACA.JK": "Bank Capital Indonesia",
    "BBHI.JK": "Allo Bank Indonesia",
    "ARTO.JK": "Bank Jago",
    "BBYB.JK": "Bank Neo Commerce",
    # ── TELCO & TOWER (8) ─────────────────────────────────────────
    "TLKM.JK": "Telkom Indonesia",
    "ISAT.JK": "Indosat Ooredoo Hutchison",
    "EXCL.JK": "XL Axiata",
    "FREN.JK": "Smartfren Telecom",
    "LINK.JK": "Link Net",
    "TBIG.JK": "Tower Bersama Infrastructure",
    "TOWR.JK": "Sarana Menara Nusantara",
    "MTEL.JK": "Dayamitra Telekomunikasi",
    # ── CONSUMER STAPLES (18) ─────────────────────────────────────
    "UNVR.JK": "Unilever Indonesia",
    "ICBP.JK": "Indofood CBP Sukses Makmur",
    "INDF.JK": "Indofood Sukses Makmur",
    # ── HEALTHCARE & PHARMA (12) ──────────────────────────────────
    "KLBF.JK": "Kalbe Farma",
    "KAEF.JK": "Kimia Farma",
    "INAF.JK": "Indofarma",
    # ── METALS & MINERALS (10) ────────────────────────────────────
    "MDKA.JK": "Merdeka Copper Gold",
    "ANTM.JK": "Aneka Tambang",
    "INCO.JK": "Vale Indonesia",
    "AMMN.JK": "Amman Mineral Internasional",
    "BREN.JK": "Barito Renewables Energy",
    # ── PLANTATION (12) ───────────────────────────────────────────
    "AALI.JK": "Astra Agro Lestari",
    "PWON.JK": "Pakuwon Jati",
    "SMRA.JK": "Summarecon Agung",
    "MKPI.JK": "Metropolitan Kentjana",
    "DMAS.JK": "Puradelta Lestari",
    "MTLA.JK": "Metropolitan Land",
    "APLN.JK": "Agung Podomoro Land",
    "WIKA.JK": "Wijaya Karya",
    "PTPP.JK": "PP Persero",
    "ADHI.JK": "Adhi Karya",
    "BTON.JK": "Betonjaya Manunggal",
    "DGIK.JK": "Nusa Konstruksi Enjiniring",
    "GJTL.JK": "Gajah Tunggal",
}
